# Generated by Django 4.2.3 on 2023-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="chatCount",
            field=models.IntegerField(default=0),
        ),
    ]
